source 'https://rubygems.org'

gem 'rails', '4.2.5.1'
gem 'rails-api'
gem 'pg'
gem 'phony_rails'
gem 'config'
gem 'rabl'
gem 'sidekiq'
gem 'whenever', require: false
gem 'kaminari'
gem 'oj'
gem 'paperclip', '~> 4.3'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
gem 'unicorn'
gem 'newrelic_rpm'

group :development do
  gem 'capistrano-rails'
  gem 'web-console', '~> 2.0'
  gem 'rubocop', require: false
  gem 'immigrant'
end

group :test do
  gem 'shoulda-matchers'
  gem 'factory_girl_rails'
  gem 'timecop'
end

group :development, :test do
  gem 'pry-byebug'
  gem 'better_errors'
  gem 'jazz_hands', github: 'nixme/jazz_hands',
                    branch: 'bring-your-own-debugger'
  gem 'rspec-rails', '~> 3.0'
end
